### ISSUE TITLE
can not load gem

### ISSUE THREAD

**Issue by se6wagner** [brighton36/counterparty_ruby#1]
when requiring the gem installed via bundler as defined in the GEMFILE 

GEMFILE
gem 'counterparty_ruby', :git => 'git://github.com/brighton36/counterparty_ruby.git'

I get the following error

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- counterparty_ruby (LoadError)
  from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
  from /Users/swagner/Development/swarm/mule_ruby/mule_ruby.rb:7:in `<class:Swarm>'
  from /Users/swagner/Development/swarm/mule_ruby/mule_ruby.rb:1:in`<main>'
[Finished in 0.2s with exit code 1]
[shell_cmd: ruby "/Users/swagner/Development/swarm/mule_ruby/mule_ruby.rb"]
[dir: /Users/swagner/Development/swarm/mule_ruby]
[path: /usr/bin:/bin:/usr/sbin:/sbin]

same is true when using irb and pry

**Comment by brighton36** [comment]
So, the gem hasn't actually been 'officially' released. But I'll have this up in the next day or two for you, and we/you should be able to load this then. Thank-you for the bug report!

**Comment by se6wagner** [comment]
cheers Chris

On January 6, 2015 at 6:00:40 PM, Chris DeRose (notifications@github.com) wrote:

So, the gem hasn't actually been 'officially' released. But I'll have this up in the next day or two for you, and we/you should be able to load this then. Thank-you for the bug report!

**Comment by brighton36** [comment]
The gem is a live ruby gem now. Version 0.9. Give that a try and see if it works? If not - reopen an issue please.
